#!/bin/bash -e

##
## bashrc: configure.sh executes when configuring interactive bash shell
##

#  Environment  {{{

  LOCAL_ENV_PATH="$ENV_PATH/bash"

  FCEDIT=vi
  FIGNORE=.o:~:.swp
  GLOBIGNORE=*.swp
  PROMPT_COMMAND=
  PROMPT_DIRTRIM=0
  TMOUT=0
  # unmodified: BASH_ENV CDPATH PS1 PS2

  PAGER=less
  TIMEFORMAT=$'\nreal %3R\tuser %3U\tsys %3S\tpcpu %P\n'

  EDITOR=vim
  LESS=
  LESSCHARSET='latin1'
  LESSHISTFILE="-"
  LESSHISTSIZE=0

# }}}

# Bash History {{{

  # duplicate lines excluded from history. See bash(1) for more options
  # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
  HISTCONTROL=ignoredups
  HISTFILE="$ENV_PATH/tmp/bash-history"
  HISTIGNORE='fg:cd *:l:ls:ll:la:gst:cdl *'
  HISTTIMEFORMAT="[%m/%d] [%T]   "

  HISTSIZE=500
  HISTFILESIZE=1000

# }}}

#  Alias/Function Setup {{{

  . "$LOCAL_ENV_PATH/functions.sh"
  . "$LOCAL_ENV_PATH/aliases.sh"

  source-config-file() {
    . "$LOCAL_ENV_PATH/${1}.sh"
  }

  source-config-file 'config'
  source-config-file 'functions'
  source-config-file 'aliases'

  unset -f source-config-file
# }}}

